In [8]:
import numpy as np


a = np.array([[ 1, 5 ,6 ,7 ,10 ,19 ,2],[1,2,3,4,5,6,7]])

#wanted outcome = [[1,2,5,6,7,10,19],[1,7,2,3,4,5,6]]



print(repr(a.shape))
ind = np.argsort(a[0],kind='mergesort',axis = 0)
print(a[0])
print(ind)
print(a[0][ind])



(2, 7)
[ 1  5  6  7 10 19  2]
[0 6 1 2 3 4 5]
[ 1  2  5  6  7 10 19]
