## loading NPY files

In [1]:
import numpy as np
import cv2
import os

from showNumpyInfo import showInfo
from memory_profiler import memory_usage


In [2]:
os.chdir('G:/Documenten/personal/school/MaNaMA_AI/thesis/implementation/dexpression/MMI_data_creation/Thesis_Christiaan_Jean/Custom_Dexpression')

In [3]:
MUG_path = "./MUG/output_npy/MUG/"
MMI_path = "./MMI/linux_output/"
CASPEAL_path = "./output_npy/CASPEAL/"
JAFFE_path = "./output_npy/JAFFE/"

In [4]:
chosenDataset = 'MUG'

In [5]:

if(chosenDataset == 'MUG'):
    data =  [np.load(MUG_path + 'X.npy'), np.load(MUG_path + 'Y.npy'), np.load(MUG_path + 'subjectIDs.npy')]
elif(chosenDataset == 'MMI'):
    data = [np.load(MMI_path + 'X.npy'), np.load(MMI_path + 'Y.npy'), np.load(MMI_path + 'subjectIDs.npy')]
elif(chosenDataset == 'CASPEAL'):
    data = [np.load(CASPEAL_path +'X.npy'), np.load(CASPEAL_path +'Y.npy'), np.load(CASPEAL_path +'subjectIDs.npy')]
elif(chosenDataset == 'JAFFE'):    
    data = [np.load(JAFFE_path + 'X.npy'), np.load(JAFFE_path + 'Y.npy'), np.load(JAFFE_path + 'subjectIDs.npy')]

## Early details


In [6]:
print(chosenDataset)
# displays: type, Dtype and shape
showInfo(data[0],'X_images_input')
showInfo(data[1],'Y_emotions_output')
showInfo(data[2],"subjectIDS")

# samples of the labels
print(data[1][:20])
# samples of the subjectIDS
print(data[2][:20])

# how much memory is used for just loading the data
mem_usage = memory_usage(-1, interval=.5, timeout=1)
str = 'Maximum memory usage is ' + repr( mem_usage)
print(str)

MUG
Name  X_images_input
type:  <class 'numpy.ndarray'>
Dtype:  uint8
shape:  (326, 224, 224, 1)
Name  Y_emotions_output
type:  <class 'numpy.ndarray'>
Dtype:  float64
shape:  (326, 7)
Name  subjectIDS
type:  <class 'numpy.ndarray'>
Dtype:  <U9
shape:  (326,)
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
['databases' 'databases' 'databases' 'databases' 'databases' 'databases'
 'databases' 'databases' 'databases' 'databases' 'databases' 'databases'
 'databases' 'databases' 'databases' 'databases' 'databases' 'databases'
 'databases' 'databases']
Maximum memory

## create emotional labels

In [13]:
angry = np.array([1.0,0.0,0.0,0.0,0.0,0.0,0.0])
neutral = np.array([0.0,1.0,0.0,0.0,0.0,0.0,0.0])
disgust = np.array([0.0,0.0,1.0,0.0,0.0,0.0,0.0])
fear = np.array([0.0,0.0,0.0,1.0,0.0,0.0,0.0])
happy = np.array([0.0,0.0,0.0,0.0,1.0,0.0,0.0])
sad = np.array([0.0,0.0,0.0,0.0,0.0,1.0,0.0])
surprise = np.array([0.0,0.0,0.0,0.0,0.0,0.0,1.0])

In [14]:
def create_emotion_list(database):
    emotion_list = []
    for i in range(len(database[1])):
        if(np.array_equal(angry,database[1][i])):
            emotion = 'angry'
            emotion_list.append(emotion)
        elif(np.array_equal(neutral,database[1][i])):
            emotion = 'neutral'
            emotion_list.append(emotion)
        elif(np.array_equal(disgust,database[1][i])):
            emotion = 'disgust'
            emotion_list.append(emotion)
        elif(np.array_equal(fear,database[1][i])):
            emotion = 'fear'
            emotion_list.append(emotion)
        elif(np.array_equal(happy,database[1][i])):
            emotion = 'happy'
            emotion_list.append(emotion)
        elif(np.array_equal(sad,database[1][i])):
            emotion = 'sad'
            emotion_list.append(emotion)
        elif(np.array_equal(surprise,database[1][i])):
            emotion = 'surprise'
            emotion_list.append(emotion)
    return emotion_list

## Veryfying emotion vs face

In [15]:
data_emotion = create_emotion_list(data)

## Printing emotion vs face imshow

In [16]:
def print_database_pics(database, emotions):
    for i in range(len(database[0])):
        cv2.imshow(database[2][i] +"i: "+ repr(i) +": "+ emotions[i], database[0][i].astype('uint8'))
        cv2.waitKey(0)
        cv2.destroyAllWindows()

In [17]:
print_database_pics(data, data_emotion)

S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S050
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044
S044


KeyboardInterrupt: 

### Storing neutral faces and corresponding subject IDs

In [18]:
def get_neutral_faces(database, emotions):
    neutral_faces = []
    subject_ID = []
    for i in range(len(database[0])):
        if(emotions[i] == 'neutral'):
            neutral_faces.append(database[0][i])
            subject_ID.append(database[2][i])
    return neutral_faces, subject_ID

In [19]:
#Index 0: pics, index 1: subject IDs
neutral_data = get_neutral_faces(data, data_emotion)

### Checking neutral faces and subject IDs


In [20]:
def print_neutral_faces(neutral_database):
    for i in range(len(neutral_database[0])):
        cv2.imshow(neutral_database[1][i], neutral_database[0][i].astype('uint8'))
        cv2.waitKey()
        cv2.destroyAllWindows()

In [21]:
print_neutral_faces(neutral_data)



KeyboardInterrupt: 