# cutFace algo

In [2]:
import cv2
import sys
import os
import numpy as np

#give grayscale image and 2D height and width of output and a facecascade
def cutFace(img,width,height,casc, database):

    try:
        if(database == 'MUG'):
            minSizeX = 100
            minSizeY = 100
        else:
            minSizeX = 100
            minSizeY = 100
        # Detect faces in the image
        faces = casc.detectMultiScale(
            img,
            scaleFactor=1.1,
            minNeighbors=5,
            minSize=(minSizeX, minSizeY),
            flags = cv2.CASCADE_SCALE_IMAGE
        )
        if(len(faces)!=0):
            for (x, y, w, h) in faces:
                if w > h :
                    he = w//2
                    wi = w//2
                else :
                    he = h//2
                    wi = h//2

                x_m = (x+w//2)
                y_m = (y+h//2)
                
                cut_image = img[y_m-he:y_m+he,x_m-wi:x_m+wi]
                cut_image = cv2.resize(cut_image,(width,height), interpolation = cv2.INTER_AREA)
        
        return cut_image

    except Exception as e:
        print(e)
   

# Alternative cutFace algo

In [3]:
# import cv2
# import os

# def cutFace(img,width,height, cascade, database):

#     try:
#         minisize = (img.shape[1],img.shape[0])
#         miniframe = cv2.resize(img, minisize)

#         faces = cascade.detectMultiScale(miniframe)
#         if(database == 'MMI'):
#             if(len(faces == 0)):
#                 img = np.rot90(img, k = 3)
#         for f in faces:
#             x, y, w, h = [ v for v in f ]
#             cv2.rectangle(img, (x,y), (x+w,y+h), (255,255,255))

#             sub_face = img[y:y+h, x:x+w]
#             sub_face = cv2.resize(sub_face,(width,height), interpolation = cv2.INTER_AREA)
#         if(len(faces)>=2):
#             cv2.imshow("frame", sub_face)
#             cv2.waitKey()
#         return sub_face
#     except Exception as e:
#         print(e)



# imports

In [4]:
from xml.dom import minidom
from glob import glob
import xml.etree.ElementTree
from lxml import etree
import os
import cv2

# get datapaths

In [5]:
data_path_CASPEAL = "C:/Users/JeanBV/Documents/databases/CAS_PEAL/CAS-PEAL-R1"
data_path_JAFFE = "C:/Users/JeanBV/Documents/databases/JAFFE_frames"
data_path_MUG = "C:/Users/JeanBV/Documents/databases/MUG/"
data_path_MMI = "C:/Users/JeanBV/Documents/databases/MMI"
data_path_CKP = "C:/Users/JeanBV/Documents/databases/CK+"

# get frames from videos with starting to ending frame

In [6]:
# def get_frames_from_vid(path):
#     cap = cv2.VideoCapture(path) #video_name is the video being called
#     cap.set(1, frame_no); # Where frame_no is the frame you want
#     ret, frame = cap.read() # Read the frame
#     cv2.imwrite("frames/"+path.split("\\")[9].split(".")[0]+".jpg", frame)     # save frame as JPEG file

In [7]:
def get_frames_from_vid(path,subject, start, end):
#     frame_dir= "Frame"
    subject_dir = subject
    list_of_frames = []
    
    #Not used right now
    
#     if not os.path.exists(frame_dir):
#         os.makedirs(frame_dir)
#     current_directory = os.path.abspath(frame_dir)
#     subject_dir = os.path.join(current_directory, subject_dir)
#     if not os.path.exists(subject_dir):
#         os.makedirs(subject_dir) 
        
    cap = cv2.VideoCapture(path) #video_name is the video being called
    
    cap.set(1,start); # Where frame_no is the frame you want
    ret, frame = cap.read() # Read the frame
    count = start
    while count <= end:
        list_of_frames.append(frame)
#       cv2.imwrite("Frame/"+subject+"/"+subject+"%d.jpg" % count, frame)     # save frame as JPEG file      
        ret,frame = cap.read()
        count += 1
    return list_of_frames

In [302]:
os.path.abspath("C:/qsdqsd/qsdqsd")

'C:\\qsdqsd\\qsdqsd'

In [8]:
def input_MMI_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, printData = 0):
    #subject counter   
    sub = 0
    lastSub = 0
    subjectID = 0
    i = 0
    dimMap = {}
    list_emotions=[]
    #intialize database path
    data_path = data_path_MMI
    #change directory to where the dB is situated
    os.chdir(data_path)
    label_expression = glob('./Sessions/*/*')
    amount_of_emotion = 0
    length_neutral_frames = 0
    length_all_frames = 0
    x_neutral = []
    x_emotion = []
    # print(os.getcwd())

    for file in label_expression:

        if(file.endswith('.avi')):
            xml_file = "."+file.split(".",-1)[1]+'.xml'
            myroot = xml.etree.ElementTree.parse(xml_file).getroot()
            for line in myroot.findall('Metatag'):
                if(line.attrib['Name'] == 'Emotion'):
                    #Extracting emotion
                    emotion_label = int(line.attrib['Value'])

            #Getting video
            video_path = os.path.abspath(file)

            #Get unique subject
            subjectID = video_path.split("\\")[-1].split(".")[0].split("-")[0]
            if subjectID != lastSub:
                sub = sub + 1
            lastSub = subjectID
            
            IDNumber = int(subjectID[1:])

            cap = cv2.VideoCapture(video_path)
            video_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            get_middle = int(video_length/2)

            lower_bound = get_middle - round(video_length/8)
            upper_bound = get_middle + round(video_length/8)

            #Get frames for emotions
            frames = get_frames_from_vid(video_path, subjectID, lower_bound, upper_bound)
            
            
            #Get neutral frames
            #First 5%
            frames_neutral_first_5 = get_frames_from_vid(video_path, subjectID, 0, int(video_length*0.015))
            #Last 5%
            frames_neutral_last_5 = get_frames_from_vid(video_path, subjectID, int(video_length*0.985), video_length)

            neutral_frames = frames_neutral_first_5 + frames_neutral_last_5
            
            X_data_before = len(X_data)
            #Neutral
            for frame in neutral_frames:
                if(frame is not None):
                    x = int(frame.shape[1])
                    if(subjectID == 'S001') or (subjectID == 'S002') or (subjectID == 'S017') :
                        sliced_image = frame[:, int(x/2):, :]
                    elif(subjectID == 'S003') or (subjectID == 'S005') or (subjectID == 'S006') or (subjectID == 'S015')or (subjectID == 'S016'):
                        sliced_image = frame[:, 0:int(x/2), :]
                    elif(subjectID == 'S021'):
                        continue
                    else:
                        sliced_image = frame
                    sliced_image = cv2.cvtColor(sliced_image, cv2.COLOR_BGR2GRAY)
                    
                    if(IDNumber > 21):
                        sliced_image = np.rot90(sliced_image, k = 3)
                        
                    X_data.append(sliced_image)
                    
            X_data_now_neutr = len(X_data)
                                     
            #Neutral
            #Get amount of neutral emotions to be added
            amount_of_neutral = X_data_now_neutr - X_data_before
            data_shape = np.zeros(amount_of_neutral).shape
            #Get Y_data
            #Neutral is characterized as a zero.
            Y_data_neutral = np.full(amount_of_neutral, 2) 
            #Get X_subID data
            X_subID_neutral = np.full(Y_data_neutral.shape, subjectID)
            i = i + amount_of_neutral

            #Store emotion label and subjectID in the corresponding lists
            Y_data.extend(Y_data_neutral)
            X_subID.extend(X_subID_neutral)

            N = N + amount_of_neutral
                
            length_x_neutral = len(X_data)
            #Emotions
            
            #These frames all have the same emotional label. They come from the same video. So it is safe to generalize all the emotions.
            for frame in frames:
                if(frame is not None) and (emotion_label >=0) and (emotion_label <=7):
                    x = int(frame.shape[1])
                    if(subjectID == 'S001') or (subjectID == 'S002') or (subjectID == 'S017') :
                        sliced_image = frame[:, int(x/2):, :]
                    elif(subjectID == 'S003') or (subjectID == 'S005') or (subjectID == 'S006') or (subjectID == 'S015')or (subjectID == 'S016'):
                        sliced_image = frame[:, 0:int(x/2), :]
                    elif(subjectID == 'S021'):
                        continue
                    else:
                        sliced_image = frame
                        
                    #Change to gray image
                    sliced_image = cv2.cvtColor(sliced_image, cv2.COLOR_BGR2GRAY)
                    if(IDNumber > 21):
                        sliced_image = np.rot90(sliced_image, k = 3)
                    X_data.append(sliced_image)
                    
            X_data_now_emotion = len(X_data)
            
            #Get amount of same emotion to be added
            amount_of_emotion = X_data_now_emotion - X_data_now_neutr

            if(emotion_label >=0) and (emotion_label <=7):
                #Mapping emotions to emotion values
                if(emotion_label == 1):
                    emotion_label_add = 1
                    emotion = 'Anger'
                    A = A + amount_of_emotion
                elif(emotion_label == 2):
                    emotion_label_add = 3
                    emotion = 'Disgust'
                    D = D + amount_of_emotion
                elif(emotion_label == 3):
                    emotion_label_add = 4
                    emotion = 'Fear '
                    F = F + amount_of_emotion
                elif(emotion_label == 4):
                    emotion_label_add = 5
                    emotion = 'Happy'
                    H = H + amount_of_emotion
                elif(emotion_label == 5):
                    emotion_label_add = 6
                    emotion = 'Saddness'
                    Sa = Sa + amount_of_emotion
                elif(emotion_label == 6):
                    emotion_label_add = 7
                    emotion = 'Surprise'
                    Su = Su + amount_of_emotion

                #Get np array size / shape
                data_shape = np.zeros(amount_of_emotion).shape
                #Get Y_data
                Y_data_emotion = np.full(data_shape, emotion_label_add)
                #Get X_subID data
                X_subID_emotion = np.full(data_shape, subjectID)
                i = i + amount_of_emotion
                Y_data.extend(Y_data_emotion)
                X_subID.extend(X_subID_emotion)

    return X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su

In [9]:
# def input_MMI_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, printData = 0):
#     #subject counter   
#     sub = 0
#     lastSub = 0
#     subjectID = 0
#     i = 0
#     dimMap = {}
#     list_emotions=[]
#     #intialize database path
#     data_path = data_path_MMI
#     emotionNr = 0
#     #change directory to where the dB is situated
#     os.chdir(data_path)
#     label_expression = glob('./Sessions/*/*')

#     # print(os.getcwd())

#     for file in label_expression[0:50]:

#         if(file.endswith('.avi')):
#             xml_file = "."+file.split(".",-1)[1]+'.xml'
#             myroot = xml.etree.ElementTree.parse(xml_file).getroot()
#             for line in myroot.findall('Metatag'):
#                 if(line.attrib['Name'] == 'Emotion'):
#                     #Extracting emotion
#                     emotionNr = line.attrib['Value']

#             #Getting video
#             video_path = os.path.abspath(file)

#             #Get unique subject
#             subjectID = video_path.split("\\")[-1].split(".")[0].split("-")[0]
#             if subjectID != lastSub:
#                 sub = sub + 1
#             lastSub = subjectID

#             cap = cv2.VideoCapture(video_path)
#             video_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#             get_middle = int(video_length/2)

#             lower_bound = get_middle - round(video_length/8)
#             upper_bound = get_middle + round(video_length/8)

#             #Get frames for emotions
#             frames = get_frames_from_vid(video_path, subjectID, lower_bound, upper_bound)
            
# #             #Get frames for neutral emotions. We expect the first 5% and last 5% of the videos to be of a neutral emotion.
# #             #First 5%
# #             frames_neutral_first_5 = get_frames_from_vid(video_path, subjectID, 0, int(videolength*0.05))
# #             #Last 5%
# #             frames_neutral_last_5 = get_frames_from_vid(video_path, subjectID, int(videolength*0.95), videolength)

# #             neutral_frames = frames_neutral_first_5 + frames_neutral_last_5
# #             X_data_neutral = frames_neutral_first_5 + frames_neutral_last_5
# #             Y_data_neutral = np.zeros(len(X_data_neutral))
# #             X_subID_neutral = np.full(Y_data_neutral.shape, subjectID)

# #             for frame in neutral_frames:
# #                 if(frame is not None):
# #                     x = int(frame.shape[1])
# #                     if(subjectID == 'S001') or (subjectID == 'S002'):
# #                         sliced_image = frame[:, int(x/2):, :]
# #                     elif(subjectID == 'S003') or (subjectID == 'S005') or (subjectID == 'S006') or (subjectID == 'S0015'):
# #                         sliced_image = frame[:, 0:int(x/2), :]
# #                     elif(subjectID == 'S021'):
# #                         continue
# #                     else:
# #                         sliced_image = frame
                

#                     x = int(frame.shape[1])
#                     if(subjectID == 'S001') or (subjectID == 'S002'):
#                         sliced_image = frame[:, int(x/2):, :]
#                     elif(subjectID == 'S003') or (subjectID == 'S005') or (subjectID == 'S006') or (subjectID == 'S0015'):
#                         sliced_image = frame[:, 0:int(x/2), :]
#                     elif(subjectID == 'S021'):
#                         continue
#                     else:
#                         sliced_image = frame

#                     sliced_image = cv2.cvtColor(sliced_image, cv2.COLOR_BGR2GRAY)
#                     emotionNr = int(emotionNr)
#                     original_emotion = emotionNr

#                     if(int(emotionNr) >=0) and (int(emotionNr) <=7):
                        
#                         #Mapping emotions to emotion values
#                         if(int(emotionNr) == 1):
#                             emotionNr = 1
#                             emotion = 'Anger'
#                             A = A + 1
#                         elif(emotionNr == 2):
#                             emotionNr = 3
#                             emotion = 'Disgust'
#                             D = D + 1
#                         elif(emotionNr == 3):
#                             emotionNr = 4
#                             emotion = 'Fear '
#                             F = F + 1
#                         elif(emotionNr == 4):
#                             emotionNr = 5
#                             emotion = 'Happy'
#                             H = H + 1
#                         elif(emotionNr == 5):
#                             emotionNr = 6
#                             emotion = 'Saddness'
#                             Sa = Sa + 1
#                         elif(emotionNr == 6):
#                             emotionNr = 7
#                             emotion = 'Surprise'
#                             Su = Su + 1

#                         #Store image and emotion label in the X_data and Y_data lists
#                         X_data.append(neutr_X)
#                         X_data.append(sliced_image)
#                         Y_data.append(emotionNr)
#                         X_subID.append(subjectID)
#                         i = i+1

#                         #load in original emotion again
#                         emotionNr = original_emotion

#     return X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su

<h3> CKP database </h3>

In [10]:
def input_CKP_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, C, printData = 0):
    #stores the current working directory path to restore at the end and goes to the given database path
    curr_path = os.getcwd()
    #subject counter   
    sub = 0
    lastSub = 0
    subjectID = 0
    i = 0
    dimMap = {}
    list_emotions=[]
    #intialize database path
    data_path = data_path_CKP
    emotionNr = 0
    #change directory to where the dB is situated
    os.chdir(data_path)
    
    label_list = glob('./Emotion/*/*/*.txt')

    X_data = [] # list of input data = climax images of emotions
    Y_data = [] # list of output data = emotion expressed in image

    X_subID = [] # list with subject Id of each X_data element 

    i = 0 #count of total amount of instances
    
    #subject counter
    sub = 0
    lastSub = 0
    subjectID = 0

    dimMap = {}


    #iterate through the list of label files, open corresponding images
    for fn in label_list[0:500]:
        str = './cohn-kanade-images'+ fn[9:-12] + '.png'
        image = cv2.imread(str)
        img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # emotion label
        file = open(fn,'r')
        fileTxt = file.read()

        emotionNr = int(fileTxt[3:4])
        #print("emotion:", emotionNr)
        file.close()

        #determine the subject
        subjectID = fn[11:14]
        if subjectID != lastSub :
            sub = sub + 1
        lastSub = subjectID 

        #determine the emotion of the image
        if(emotionNr == 0):
            emotion = 'Neutral'
            N = N + 1
        elif(emotionNr == 1):
            emotion = 'Anger'
            A = A + 1
        elif(emotionNr == 2):
            emotion = 'Contempt'
            C = C + 1
        elif(emotionNr == 3):
            emotion = 'Disgust'
            D = D + 1
        elif(emotionNr == 4):
            emotion = 'Fear '
            F = F + 1
        elif(emotionNr == 5):
            emotion = 'Happy'
            H = H + 1
        elif(emotionNr == 6):
            emotion = 'Saddness'
            Sa = Sa + 1
        else:
            emotion = 'Surprise'
            Su = Su + 1

        #Store image and emotion label in the X_data and Y_data lists
        X_data.append(img)
        Y_data.append(emotionNr)
        X_subID.append(subjectID)
        i = i+1

    return X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su, C

<h3> MUG database </h3>

In [11]:
import os

In [ ]:
#intialize database path
data_path = data_path_MUG

#change directory to where the dB is situated
os.chdir(data_path)

#The different emotions are stored in different folders accross the directory
label_expression = glob('./*/*/*/')

In [ ]:


for image in label_expression:
    emotion_label = image.split("\\")[2]
    save_path = os.path.abspath(image)
    #Get list of images
    image_list = os.listdir(image)
    for image in image_list:
        if(image.endswith(".jpg")) or (image.endswith(".avi")):
            ok = True
        else:
            ok = False
    if(ok):
        print(emotion_label)
        



In [12]:
def input_MUG_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, printData = 0):
    #subject counter   
    sub = 0
    lastSub = 0
    subjectID = 0
    i = 0
    dimMap = {}
    
    #intialize database path
    data_path = data_path_MUG

    #change directory to where the dB is situated
    os.chdir(data_path)
    
    #The different emotions are stored in different folders accross the directory
    label_expression = glob('./*/*/*/')
    label_session_expression = glob('./*/session*/*/*/')
    

#     for image in label_session_expression[0:5]:
        
#         #Get amount of images per emotion
#         amount_of_images = len(os.listdir(image))
        
#         #Get emotion label
        
#         emotion_label = image.split("\\")[3]
#         if(emotion_label != 'mixed'):
            
#             #Get middle image
#             middle_image = round(amount_of_images/2)    
            
#             #Create bounds
#             lower_bound = middle_image - round(amount_of_images/8)
#             upper_bound = middle_image + round(amount_of_images/8)
            
#             #Get list of images
#             image_list =(os.listdir(image))
            
#             #Bound the list of images
#             image_list_bound = (image_list[lower_bound:upper_bound])
#             for k in range(len(image_list_bound)):
#                 img_path = (os.path.abspath(image)+"\\"+image_list_bound[k])
#                 image_rd = cv2.imread(img_path)
#                 img = cv2.cvtColor(image_rd, cv2.COLOR_BGR2GRAY)

#                  #Get emotion labels
#                 if(emotion_label == 'neutral'):
#                     emotion_label_add = 2
#                     emotion = 'Neutral'
#                     N = N + 1
#                 elif(emotion_label == 'anger'):
#                     emotion_label_add = 1
#                     emotion = 'Anger'
#                     A = A + 1
#                 elif(emotion_label == 'disgust'):
#                     emotion_label_add = 3
#                     emotion = 'Disgust'
#                     D = D + 1
#                 elif(emotion_label == 'fear'):
#                     emotion_label_add = 4
#                     emotion = 'Fear '
#                     F = F + 1
#                 elif(emotion_label == 'happiness'):
#                     emotion_label_add = 5
#                     emotion = 'Happy'
#                     H = H + 1
#                 elif(emotion_label == 'sadness'):
#                     emotion_label_add = 6
#                     emotion = 'Saddness'
#                     Sa = Sa + 1
#                 elif(emotion_label == 'surprise'):
#                     emotion_label_add = 7
#                     emotion = 'Surprise'
#                     Su = Su + 1

#                 subjectID = img_path.split("\\")[6]
#                 if subjectID != lastSub :
#                     sub = sub + 1
#                 lastSub = subjectID 

#                 # store image and emotion label in the X_data and Y_data lists
#                 X_data.append(img)               
#                 Y_data.append(emotion_label_add)
#                 X_subID.append(subjectID)
#                 i = i+1

    for image in label_expression:
        save_path = os.path.abspath(image)
        amount_of_images = len(os.listdir(image))
        emotion_label = image.split("\\")[2]
        #Get list of images
        image_list = os.listdir(image)
        for image in image_list:
            if(image.endswith(".jpg")) or (image.endswith(".avi")):
                ok = True
            else:
                ok = False
        if(ok):
            #Exclude mixed emotion
            if(emotion_label != 'mixed'):
                #Get the middle_image
                middle_image = round(amount_of_images/2)

                #Create bounds
                lower_bound = middle_image - round(amount_of_images/8)
                upper_bound = middle_image + round(amount_of_images/8)
                #Bound the list of images
                image_list_bound = (image_list[lower_bound:upper_bound])
                for k in range(len(image_list_bound)):
                    img_path = (save_path+"\\"+image_list_bound[k])
                    if(img_path.endswith("jpg")):
                        print("image path:", img_path)
                        image_rd = cv2.imread(img_path)
                        img = cv2.cvtColor(image_rd, cv2.COLOR_BGR2GRAY)

                    original_emotion = emotion_label
                    if(emotion_label == 'neutral'):
                        emotion_label_add = 2
                        emotion = 'Neutral'
                        N = N + 1
                    elif(emotion_label == 'anger'):
                        emotion_label_add = 1
                        emotion = 'Anger'
                        A = A + 1
                    elif(emotion_label == 'disgust'):
                        emotion_label_add = 3
                        emotion = 'Disgust'
                        D = D + 1
                    elif(emotion_label == 'fear'):
                        emotion_label_add = 4
                        emotion = 'Fear'
                        F = F + 1
                    elif(emotion_label == 'happiness'):
                        emotion_label_add = 5
                        emotion = 'Happy'
                        H = H + 1
                    elif(emotion_label == 'sadness'):
                        emotion_label_add = 6
                        emotion = 'Saddness'
                        Sa = Sa + 1
                    elif(emotion_label == 'surprise'):
                        emotion_label_add = 7
                        emotion = 'Surprise'
                        Su = Su + 1

                    #Get subject
                    subjectID = img_path.split("\\")[6]
                    if subjectID != lastSub :
                        sub = sub + 1
                    lastSub = subjectID 

                    # store image and emotion label in the X_data and Y_data lists
                    X_data.append(img)
                    Y_data.append(emotion_label_add)
                    X_subID.append(subjectID)
                    i = i+1
                
    return X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su



<h3> JAFFE database </h3>

In [13]:
def input_JAFFE_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, printData = 0):

    #subject counter
    sub = 0
    lastSub = 0
    subjectID = 0
    i = 0
    dimMap = {}
    #intialize database path
    data_path = data_path_JAFFE

    #change directory to where the dB is situated
    os.chdir(data_path)
    print(os.path.abspath(data_path))

    #get the emotion expressions
    label_expression = glob('./*.tiff')
    for fn in label_expression:

        #get emotion
        emotion_label = fn.split(".")[2][0:2]

        #load image
        image = cv2.imread(fn)
        img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        if(emotion_label == 'NE'):
            emotion_label_add = 2
            emotion = 'Neutral'
            N = N + 1
        elif(emotion_label == 'AN'):
            emotion_label_add = 1
            emotion = 'Anger'
            A = A + 1
        elif(emotion_label == 'DI'):
            emotion_label_add = 3
            emotion = 'Disgust'
            D = D + 1
        elif(emotion_label == 'FE'):
            emotion_label_add =4
            emotion = 'Fear '
            F = F + 1
        elif(emotion_label == 'HA'):
            emotion_label_add =5
            emotion = 'Happy'
            H = H + 1
        elif(emotion_label == 'SA'):
            emotion_label_add =6
            emotion = 'Saddness'
            Sa = Sa + 1
        elif(emotion_label == 'SU'):
            emotion_label_add =7
            emotion = 'Surprise'
            Su = Su + 1

        #get subjectID
        subjectID = fn.split(".")[1][1:]
        if subjectID != lastSub:
            sub = sub + 1
        lastSub = subjectID

        #store image and emotion label in the X_data and Y_data lists
        X_data.append(img)
        Y_data.append(emotion_label_add)
        X_subID.append(subjectID)
        i = i+1
    return X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su

<h3> CASPEAL database </h3>

In [14]:
def input_CASPEAL_database(X_data, Y_data, X_subID, N, A, H, Su, printData = 0):

    #subject counter
    sub = 0
    lastSub = 0
    subjectID = 0
    i = 0
    dimMap = {}
    
    #intialize database path
    data_path = data_path_CASPEAL

    #change directory to where the dB is situated
    os.chdir(data_path)

    #get the emotion expressions
    label_expression = glob('./FRONTAL/Expression/*.tif')
    label_neutral = glob('./FRONTAL/Normal/*.tif')

    label_total = label_expression + label_neutral
    #remove unused emotions. This way we don't loop through unneeded emotions.
    for remove_image in label_total:
        if(remove_image.split("+")[2].split("_")[1][1] == "C") or (remove_image.split("+")[2].split("_")[1][1] == "O"):
            label_total.remove(remove_image)
            
    for fn in label_total:
        #Get emotion number
        emotion_label = fn.split("+")[2].split("_")[1][1]
        
        #Load the imae
        image = cv2.imread(fn)
        img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        #Get emotion labels
        if(emotion_label == 'N'):
            emotion_label_add = 2
            emotion = 'Neutral'
            N = N + 1
        elif(emotion_label == 'F'):
            emotion_label_add = 1
            emotion = 'Anger'
            A = A + 1
        elif(emotion_label == 'L'):
            emotion_label_add = 5
            emotion = 'Happy'
            H = H + 1
        elif(emotion_label == 'S'):
            emotion_label_add = 7
            emotion = 'Surprise'
            Su = Su + 1

        #Get subject
        subjectID = fn.split("\\")[1].split("_")[1]
        if subjectID != lastSub :
            sub = sub + 1
        lastSub = subjectID 

        # store image and emotion label in the X_data and Y_data lists
        X_data.append(img)
        Y_data.append(emotion_label_add)
        X_subID.append(subjectID)
        i = i+1

    return X_data, Y_data, X_subID, sub, i, N, A, H, Su

<h3> Load data algo </h3>

In [15]:
import numpy as np
import cv2
import scipy as sc
# import matplotlib.pyplot as plt
from glob import glob 
import re
import os

import tflearn

def load_data(database): 
        
    #stores the current working directory path to restore at the end.
    curr_path = os.getcwd()
    
    #Initialization
    X_data = [] # list of input data = climax images of emotions
    Y_data = [] # list of output data = emotion expressed in image
    X_subID = [] # list with subject Id of each X_data element 

    i = 0 #count of total amount of instances

    #Count per emotion
    N = 0 # Neutral
    A = 0 # Anger
    C = 0 # Contempt
    D = 0 # Disgust
    F = 0 # Feard
    H = 0 # Happy
    Sa = 0# Saddness
    Su = 0# Surprise

    #Get X_data, Y_data, and other details of each of the databases
    #Since the data is differently distributed accross the different databases, seperate functions are created 
    if(database == "CASPEAL"):
        X_data, Y_data, X_subID, sub, i, N, A, H, Su = input_CASPEAL_database(X_data, Y_data, X_subID, N, A, H, Su)

    if(database == "MUG"):
        X_data, Y_data, X_subID, sub, i, N, A, D, H,F, Sa, Su = input_MUG_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F)

    if(database == "JAFFE"):
        X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su = input_JAFFE_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F)

    if(database == "MMI"):
        from time import time
        t0 = time()
        X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su = input_MMI_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F)
        t1 = time()
        print('function vers1 takes %f' %(t1-t0))

    if(database == "CKP"):
        X_data, Y_data, X_subID, sub, i, N, A, D, H, F, Sa, Su, C = input_CKP_database(X_data, Y_data, X_subID, N, A, D, H, Sa, Su, F, C)
        
    #show stattistics
    print("--------- Overal stattistics ---------  ")
    print("amount of Subjects  : %d" % sub)
    print("amount of Instances : %d" % i)
    print("code = 0 = Neutral    %d instances: %.2f"  % (N,((float(N)/i)*100)))
    print("code = 1 = Anger      %d instances: %.2f"  % (A,((float(A)/i)*100)))
    print("code = 2 = Contempt   %d instances: %.2f"  % (C,((float(C)/i)*100)))
    print("code = 3 = Disgust    %d instances: %.2f"  % (D,((float(D)/i)*100)))
    print("code = 4 = Fear       %d instances: %.2f"  % (F,((float(F)/i)*100)))
    print("code = 5 = Happy      %d instances: %.2f"  % (H,((float(H)/i)*100)))
    print("code = 6 = Saddness   %d instances: %.2f"  % (Sa,((float(Sa)/i)*100)))
    print("code = 7 = Surprise   %d instances: %.2f"  % (Su,((float(Su)/i)*100)))
    print("--------- dimensions ---------  ")

    print("--------- last elements in lists ---------  ")
    print("length X_data" + repr(len(X_data))) 
    print("length Y_data" + repr(len(Y_data))) 

#     plt.figure('last image')
#     plt.imshow(X_data[len(X_data)-1], cmap='gray')#, interpolation='nearest');
#     plt.show()

    print("length Y_data " + repr(Y_data[len(Y_data)-1])) 
    print("image type " + repr(type(Y_data[len(Y_data)-1]))) 

    #Original path restored
    os.chdir(curr_path)

    return [X_data,Y_data,X_subID]  

C:\Users\JeanBV\Miniconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


curses is not supported on this machine (please install/reinstall curses for an optimal experience)


# CREATE NPY

In [60]:
import copy
def load_formated_data(database, printData = 0, cascPath = "C:/Users/JeanBV/Documents/Thesis_Christiaan_Jean/Custom_Dexpression/haarcascade.xml"):

    data = load_data(database)
#     print("test")
    #data[0] = X images
    #data[2] = Y emotion labels
    #data[3] = subject Ids
#     print("data:", data)
    images = data[0]
    emotion_labels = data[1]
    emotion_labels_new = copy.deepcopy(emotion_labels)
    subjectID = copy.deepcopy(data[2])
    # cut faces from each images and resize (downsample) to input dimension
    X_gray = []
    X_test = []

    # Create the haar cascade
    faceCascade = cv2.CascadeClassifier(cascPath)

    
    for i in range(0,len(images)):
        cut_img = cutFace(images[i],224,224,faceCascade, database)
        #Be sure that cut_img is initialized
        if(cut_img is not None):
            X_gray = np.append(X_gray,cut_img)
        else:
            emotion_labels_new.remove(emotion_labels_new[i])
            subjectID.remove(subjectID[i])
    #Resize to 224x224 image for input of neural networkCKE
    X_gray = X_gray.reshape([-1,224,224,1])

    # reformprint(at the emotionlabels to create a vector of 7 zeros only one of these elements is set to 1 indicating the emotion label
    labels = []

    for lab in emotion_labels_new:
        inst = np.zeros(7)
        inst[lab-1] = 1
        #print (inst)
        labels = np.append(labels,inst)

    print("size Y 2: " + repr(labels.shape))

    labels = labels.reshape([-1,7])

    print("size labels flatten: " + repr(len(labels)))
    print("size labels shape: " + repr(labels.shape))
    print("type labels: " + repr(type(labels)))

    outputData = [X_gray,labels,subjectID]

    print("ouputData", outputData)
    return outputData


    #data = load_formated_database(dataPath,0)

def create_formated_data(database, printData = 0, cascPath = "C:/Users/JeanBV/Documents/Thesis_Christiaan_Jean/Custom_Dexpression/haarcascade.xml" , databasePath = 'C:/Users/JeanBV/Documents/Thesis_Christiaan_Jean/Custom_Dexpression/'):
   
    data = load_formated_data(database, printData, cascPath)
    
    os.chdir(databasePath)
    print("making dB")
  
    #Creating directories to save the npy files of the database
    database = database
    npy_folder = "output_npy"
    if not os.path.exists(npy_folder):
        os.makedirs(npy_folder)

    current_directory = os.path.abspath(npy_folder)
    subject_dir = os.path.join(current_directory, database) #The rule to get the folder INSIDE the folder
    if not os.path.exists(subject_dir):
        os.makedirs(subject_dir)
   
    X_data = data[0].astype('uint8')
    np.save(subject_dir+"\\"+database+'_X.npy',X_data)
    np.save(subject_dir+"\\"+database+'_Y.npy',data[1])
    np.save(subject_dir+"\\"+database+'_subjectIDs.npy',data[2])



In [17]:
create_formated_data('MUG')

image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\anger\take000\img_0037.jpg
imag

image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take000\img_0059.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\take001\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\disgust\t

image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take002nsg\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take002nsg\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take002nsg\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take002nsg\img_0048.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take002nsg\img_0049.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take003nsg\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\fear\take

image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\happiness\take003\img_0039.jpg
image path: C:\Users\JeanBV\Documents\datab

image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0118.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0119.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0120.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0121.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0122.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0123.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0124.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0125.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0126.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take006nsg\img_0127.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\sadness\take007nsg\img_0199.jpg
image path: C:\Users\JeanBV\Docu

image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\001\surprise\take003\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\00

image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\take002\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\disgust\t

image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\006\sadness\t

image path: C:\Users\JeanBV\Documents\databases\MUG\007\anger\take002\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\anger\take002\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\anger\take002\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\anger\take002\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\anger\take002\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0022.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\disgust\take000\img

image path: C:\Users\JeanBV\Documents\databases\MUG\007\fear\take002\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\fear\take002\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\happiness\take000\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\0

image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take002\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take002\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\take002\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\007\sadness\t

image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take001\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\anger\take002\img_0032.jpg
imag

image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0048.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take000\img_0049.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take001\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take001\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\fear\take001\img_0029.jpg
image path: C:\U

image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\happiness\take002\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\neutral\take000\img_0016.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\neutral\take000\img_0017.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\neutral\take000\img_0018.jpg
image path: C:\Users\JeanBV\Documents\databases\M

image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\008\surprise\take001\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\00

image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take001\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0014.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0015.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0016.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0017.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0018.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0019.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0020.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0021.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0022.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\disgust\take002\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\happiness

image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0020.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0021.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0022.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\sadness\take003\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\surprise\take000\img_0021.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\surprise\take000\img_0022.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\010\surpris

image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\disgust\take000end\img_0038.jpg
image path: C:\Users\JeanBV\Docu

image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0022.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\happiness\take002\img_0029.jpg
image path: C:\Users\JeanBV\Documents\datab

image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\013\surprise\take000nsg\img_0042.jpg
image path: C:\Users\

image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take002\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take002\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take002\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take002\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\take002\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\disgust\t

image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take002\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take003\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take003\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take003\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\062\happiness\take003\img_0026.jpg
image path: C:\Users\JeanBV\Documents\datab

image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\anger\take001\img_0047.jpg
imag

image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take002\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\063\happiness\take002\img_0027.jpg
image path: C:\Users\JeanBV\Documents\datab

image path: C:\Users\JeanBV\Documents\databases\MUG\063\surprise\take005nsg\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0023.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0024.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0025.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0026.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\anger\take000\img_0033.jp

image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0048.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0049.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0050.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take002nsg\img_0051.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take003nsg\img_0027.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take003nsg\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take003nsg\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take003nsg\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\disgust\take003nsg\img_0031.jpg
image path: C:\Users\JeanBV\Docu

image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\064\surprise\take002\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\anger\take000\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\anger\take000\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\anger\take000\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\anger\t

image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0028.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0029.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0030.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0031.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0032.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0033.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0034.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0035.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0036.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0037.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\disgust\t

image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0049.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0050.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0051.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0052.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0053.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0054.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0055.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0056.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0057.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0058.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0059.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\fear\take003\img_0060.jpg
image path: C:\U

image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0130.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0131.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0132.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0133.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0134.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0135.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0136.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0137.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0138.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0139.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\happiness\take004\img_0140.jpg
image path: C:\Users\JeanBV\Documents\datab

image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0038.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0039.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0040.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0041.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0042.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0043.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0044.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0045.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0046.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0047.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\082\surprise\take001\img_0048.jpg
image path: C:\Users\JeanBV\Documents\databases\MUG\08

## Loading numpy file

In [1]:
import numpy as np
import os

In [2]:
os.chdir('C:/Users/JeanBV/Documents/Thesis_Christiaan_Jean/Custom_Dexpression')

In [3]:
MUG =  [np.load('./output_npy/MUG/MUG_X.npy'), np.load('./output_npy/MUG/MUG_Y.npy'), np.load('./output_npy/MUG/MUG_subjectIDs.npy')]
# MMI = [np.load('./output_npy/MMI/MMI_X.npy'), np.load('./output_npy/MMI/MMI_Y.npy'), np.load('./output_npy/MMI/MMI_subjectIDs.npy')]
# CASPEAL = [np.load('./output_npy/CASPEAL/CASPEAL_X.npy'), np.load('./output_npy/CASPEAL/CASPEAL_Y.npy'), np.load('./output_npy/CASPEAL/CASPEAL_subjectIDs.npy')]
# JAFFE = [np.load('./output_npy/JAFFE/JAFFE_X.npy'), np.load('./output_npy/JAFFE/JAFFE_Y.npy'), np.load('./output_npy/JAFFE/JAFFE_subjectIDs.npy')]

## Testing

### Creating emotional labels

In [4]:

angry = np.array([1.0,0.0,0.0,0.0,0.0,0.0,0.0])
neutral = np.array([0.0,1.0,0.0,0.0,0.0,0.0,0.0])
disgust = np.array([0.0,0.0,1.0,0.0,0.0,0.0,0.0])
fear = np.array([0.0,0.0,0.0,1.0,0.0,0.0,0.0])
happy = np.array([0.0,0.0,0.0,0.0,1.0,0.0,0.0])
sad = np.array([0.0,0.0,0.0,0.0,0.0,1.0,0.0])
surprise = np.array([0.0,0.0,0.0,0.0,0.0,0.0,1.0])

In [5]:
def create_emotion_list(database):
    emotion_list = []
    for i in range(len(database[1])):
        if(np.array_equal(angry,database[1][i])):
            emotion = 'angry'
            emotion_list.append(emotion)
        elif(np.array_equal(neutral,database[1][i])):
            emotion = 'neutral'
            emotion_list.append(emotion)
        elif(np.array_equal(disgust,database[1][i])):
            emotion = 'disgust'
            emotion_list.append(emotion)
        elif(np.array_equal(fear,database[1][i])):
            emotion = 'fear'
            emotion_list.append(emotion)
        elif(np.array_equal(happy,database[1][i])):
            emotion = 'happy'
            emotion_list.append(emotion)
        elif(np.array_equal(sad,database[1][i])):
            emotion = 'sad'
            emotion_list.append(emotion)
        elif(np.array_equal(surprise,database[1][i])):
            emotion = 'surprise'
            emotion_list.append(emotion)
    return emotion_list

### Verifying emotion vs face

In [11]:
MUG_emotion = create_emotion_list(MUG)

In [12]:
# MUG_emotion_2 = create_emotion_list(YFC_Y)

### Printing emotion vs face imshow

In [13]:
def print_database_pics(database, emotions):
    for i in range(len(database[0])):
        cv2.imshow("Emotion: "+ emotions[i], database[0][i].astype('uint8'))
        cv2.waitKey(0)
        cv2.destroyAllWindows()

In [14]:
# print_database_pics(MUG, MUG_emotion)

### Storing neutral faces and corresponding subject IDs

In [15]:
def get_neutral_faces(database, emotions):
    neutral_faces = []
    subject_ID = []
    for i in range(len(database[0])):
        if(emotions[i] == 'neutral'):
            neutral_faces.append(database[0][i])
            subject_ID.append(database[2][i])
    return neutral_faces, subject_ID

In [16]:
#Index 0: pics, index 1: subject IDs
neutral_MUG = get_neutral_faces(MUG, MUG_emotion)

### Checking neutral faces and subject IDs

In [18]:
def print_neutral_faces(neutral_database, print = 0):
    for i in range(len(neutral_database[0])):
        cv2.imshow(neutral_database[1][i], neutral_database[0][i].astype('uint8'))
        cv2.waitKey()
        cv2.destroyAllWindows()
    if(print == 1):
        print_neutral_faces(neutral_MUG)

In [19]:
import sys

sys.path.insert(0,'C:/Users/JeanBV/Documents/TFLearn_2/age-gender-estimation')

In [20]:
import os
import cv2
import dlib
import numpy as np
import argparse
from contextlib import contextmanager
from wide_resnet import WideResNet
from keras.utils.data_utils import get_file

pretrained_model = "https://github.com/yu4u/age-gender-estimation/releases/download/v0.5/weights.18-4.06.hdf5"
modhash = '89f56a39a78454e96379348bddd78c0d'

#Loading in CAS_PEAL dB first
ages_arr=[]
# CAS_PEAL_img = CAS_PEAL_filepaths_subj()
# ages_arr = CAS_PEAL_img

img_arr = []
def draw_label(image, point, label, font=cv2.FONT_HERSHEY_SIMPLEX,
               font_scale=1, thickness=2):
    size = cv2.getTextSize(label, font, font_scale, thickness)[0]
    x, y = point
    cv2.rectangle(image, (x, y - size[1]), (x + size[0], y), (255, 0, 0), cv2.FILLED)
    cv2.putText(image, label, point, font, font_scale, (255, 255, 255), thickness)


def load_images(depth = 16, k = 8, weight_file = None):
    if not weight_file:
        weight_file = get_file("weights.18-4.06.hdf5", pretrained_model, cache_subdir="pretrained_models",
                               file_hash=modhash, cache_dir=os.path.dirname(os.path.abspath('C:/Users/JeanBV/Documents/TFLearn_2/age-gender-estimation/pretrained_models')))
    
    # for face detection
    detector = dlib.get_frontal_face_detector()

    # load model and weights
    img_size = 64
    model = WideResNet(img_size, depth=depth, k=k)()
    model.load_weights(weight_file)
    
    MMI_pics = neutral_MUG

#     for pic in MUG_pics[0:20]:
    for i in range(len(MMI_pics[0])):
        classified_MMI_pics = main("MMI",MMI_pics[0][i], MMI_pics[1][i], detector, model, img_size)
#     for pic in DISFA_pics:
#         array_DISFA_pics = main("DISFA", pic, detector, model, img_size)
#     for pic in MMI_pics:
#         array_MNIST_pics = main("MMI", pic, detector, model, img_size)
#     for pic in CKE_pics:
#         array_CKE_pics = main("CKE", pic, detector, model, img_size)
#     for pic in JAFFE_pics:
#         array_JAFFE_pics = main("JAFFE", pic, detector, model, img_size)
   
    return classified_MMI_pics
def main(src, img, subjectID, detector, model, img_size):
    
    #Get BGR in order for the detector to work.
    input_img = cv2.cvtColor(img.astype('uint8'), cv2.COLOR_GRAY2BGR)
    cut_image = cv2.resize(input_img, (64, 64), interpolation = cv2.INTER_AREA)
    cut_image = np.expand_dims(cut_image, axis=0)
    print(img)
#     detected = detector(input_img, 1)
#     img_h, img_w, _ = np.shape(input_img)
#     faces = np.empty((len(detected), img_size, img_size, 3))
    
#     print(faces.shape)
    # predict ages and genders of the detected faces
    results = model.predict(cut_image)
    predicted_genders = results[0]
    ages = np.arange(0, 101).reshape(101, 1)
    predicted_ages = results[1].dot(ages).flatten()
        
#     cv2.imshow("image", cut_image)
#     cv2.waitKey()
#     cv2.destroyAllWindows()
    print("genders: ", predicted_genders)
    print("ages: ", predicted_ages[0])
    # draw results
    if predicted_genders[0][0] > 0.5:
        gender = "F"
    else:
        gender = "M"
    
    ages_arr.append([src, subjectID, int(predicted_ages[0]), gender])
    return ages_arr


## Classifcation

In [21]:
#Load data
MUG_data = load_images()

[[[ 6.]
  [ 6.]
  [ 7.]
  ...
  [35.]
  [38.]
  [35.]]

 [[ 7.]
  [ 9.]
  [ 5.]
  ...
  [36.]
  [36.]
  [37.]]

 [[ 9.]
  [ 6.]
  [ 3.]
  ...
  [38.]
  [40.]
  [38.]]

 ...

 [[11.]
  [ 8.]
  [ 3.]
  ...
  [ 7.]
  [ 4.]
  [ 3.]]

 [[14.]
  [ 5.]
  [ 5.]
  ...
  [ 5.]
  [ 4.]
  [ 4.]]

 [[12.]
  [ 4.]
  [ 5.]
  ...
  [ 6.]
  [ 5.]
  [ 2.]]]
genders:  [[0.84887105 0.151129  ]]
ages:  23.20452834592288
[[[ 6.]
  [ 7.]
  [ 5.]
  ...
  [37.]
  [36.]
  [36.]]

 [[ 8.]
  [ 6.]
  [ 4.]
  ...
  [36.]
  [38.]
  [37.]]

 [[ 6.]
  [ 3.]
  [ 7.]
  ...
  [35.]
  [39.]
  [40.]]

 ...

 [[12.]
  [ 6.]
  [ 3.]
  ...
  [ 6.]
  [ 4.]
  [ 5.]]

 [[12.]
  [ 6.]
  [ 3.]
  ...
  [ 7.]
  [ 4.]
  [ 4.]]

 [[ 7.]
  [ 4.]
  [ 4.]
  ...
  [ 5.]
  [ 4.]
  [ 3.]]]
genders:  [[0.84816056 0.15183944]]
ages:  23.441038106662745
[[[ 8.]
  [ 7.]
  [ 6.]
  ...
  [37.]
  [36.]
  [36.]]

 [[ 7.]
  [ 9.]
  [ 3.]
  ...
  [37.]
  [37.]
  [36.]]

 [[ 7.]
  [ 7.]
  [ 5.]
  ...
  [37.]
  [38.]
  [39.]]

 ...

 [[14.]
  [ 7.]
  [

genders:  [[0.13244243 0.8675575 ]]
ages:  24.496308948549995
[[[68.]
  [72.]
  [74.]
  ...
  [59.]
  [59.]
  [59.]]

 [[70.]
  [75.]
  [75.]
  ...
  [55.]
  [58.]
  [59.]]

 [[72.]
  [73.]
  [73.]
  ...
  [59.]
  [57.]
  [58.]]

 ...

 [[ 6.]
  [ 6.]
  [ 4.]
  ...
  [13.]
  [10.]
  [14.]]

 [[ 7.]
  [ 7.]
  [ 6.]
  ...
  [15.]
  [10.]
  [14.]]

 [[ 8.]
  [11.]
  [10.]
  ...
  [13.]
  [13.]
  [11.]]]
genders:  [[0.16099103 0.839009  ]]
ages:  24.345107999586617
[[[71.]
  [74.]
  [76.]
  ...
  [61.]
  [58.]
  [59.]]

 [[70.]
  [73.]
  [74.]
  ...
  [55.]
  [58.]
  [60.]]

 [[72.]
  [75.]
  [73.]
  ...
  [57.]
  [57.]
  [56.]]

 ...

 [[ 8.]
  [ 5.]
  [ 4.]
  ...
  [13.]
  [12.]
  [14.]]

 [[ 8.]
  [ 5.]
  [ 4.]
  ...
  [15.]
  [ 8.]
  [11.]]

 [[ 7.]
  [ 9.]
  [10.]
  ...
  [18.]
  [11.]
  [12.]]]
genders:  [[0.14560209 0.85439795]]
ages:  24.5669035464598
[[[72.]
  [68.]
  [68.]
  ...
  [59.]
  [59.]
  [58.]]

 [[69.]
  [70.]
  [72.]
  ...
  [57.]
  [58.]
  [57.]]

 [[73.]
  [71.]
  [7

genders:  [[0.07320814 0.92679185]]
ages:  27.85654580315895
[[[77.]
  [72.]
  [72.]
  ...
  [57.]
  [57.]
  [54.]]

 [[77.]
  [72.]
  [73.]
  ...
  [55.]
  [56.]
  [52.]]

 [[75.]
  [76.]
  [73.]
  ...
  [53.]
  [55.]
  [52.]]

 ...

 [[60.]
  [60.]
  [60.]
  ...
  [38.]
  [39.]
  [39.]]

 [[62.]
  [59.]
  [59.]
  ...
  [40.]
  [37.]
  [41.]]

 [[59.]
  [56.]
  [56.]
  ...
  [40.]
  [41.]
  [40.]]]
genders:  [[0.07876988 0.9212301 ]]
ages:  27.190331416510162
[[[75.]
  [77.]
  [75.]
  ...
  [56.]
  [54.]
  [51.]]

 [[76.]
  [75.]
  [75.]
  ...
  [54.]
  [55.]
  [54.]]

 [[77.]
  [76.]
  [73.]
  ...
  [53.]
  [55.]
  [57.]]

 ...

 [[58.]
  [59.]
  [58.]
  ...
  [39.]
  [39.]
  [38.]]

 [[60.]
  [62.]
  [60.]
  ...
  [39.]
  [37.]
  [37.]]

 [[60.]
  [60.]
  [61.]
  ...
  [39.]
  [39.]
  [39.]]]
genders:  [[0.05622959 0.9437704 ]]
ages:  27.533945654875424
[[[75.]
  [76.]
  [76.]
  ...
  [57.]
  [57.]
  [54.]]

 [[75.]
  [72.]
  [75.]
  ...
  [54.]
  [53.]
  [54.]]

 [[76.]
  [72.]
  [

genders:  [[0.1897237  0.81027627]]
ages:  21.83820966705025
[[[109.]
  [109.]
  [117.]
  ...
  [ 72.]
  [ 69.]
  [ 69.]]

 [[109.]
  [109.]
  [117.]
  ...
  [ 72.]
  [ 69.]
  [ 69.]]

 [[111.]
  [111.]
  [114.]
  ...
  [ 69.]
  [ 64.]
  [ 64.]]

 ...

 [[ 94.]
  [ 94.]
  [ 89.]
  ...
  [110.]
  [102.]
  [102.]]

 [[ 86.]
  [ 86.]
  [ 93.]
  ...
  [106.]
  [111.]
  [111.]]

 [[ 86.]
  [ 86.]
  [ 93.]
  ...
  [106.]
  [111.]
  [111.]]]
genders:  [[0.5208249 0.4791751]]
ages:  36.743191029614536
[[[ 55.]
  [ 54.]
  [ 54.]
  ...
  [ 38.]
  [ 36.]
  [ 38.]]

 [[ 56.]
  [ 52.]
  [ 53.]
  ...
  [ 37.]
  [ 38.]
  [ 39.]]

 [[ 53.]
  [ 52.]
  [ 53.]
  ...
  [ 37.]
  [ 40.]
  [ 38.]]

 ...

 [[ 43.]
  [ 40.]
  [ 41.]
  ...
  [122.]
  [120.]
  [122.]]

 [[ 40.]
  [ 41.]
  [ 40.]
  ...
  [124.]
  [125.]
  [121.]]

 [[ 42.]
  [ 41.]
  [ 41.]
  ...
  [124.]
  [124.]
  [123.]]]
genders:  [[0.17165607 0.82834387]]
ages:  21.96988820003753
[[[ 52.]
  [ 52.]
  [ 52.]
  ...
  [ 38.]
  [ 39.]
  [ 41.]]



genders:  [[0.6849163  0.31508368]]
ages:  21.380850355205894
[[[48.]
  [47.]
  [47.]
  ...
  [35.]
  [33.]
  [34.]]

 [[47.]
  [48.]
  [45.]
  ...
  [31.]
  [33.]
  [33.]]

 [[48.]
  [44.]
  [45.]
  ...
  [33.]
  [33.]
  [34.]]

 ...

 [[37.]
  [37.]
  [36.]
  ...
  [22.]
  [20.]
  [21.]]

 [[35.]
  [36.]
  [40.]
  ...
  [24.]
  [22.]
  [22.]]

 [[37.]
  [34.]
  [37.]
  ...
  [24.]
  [23.]
  [24.]]]
genders:  [[0.67554677 0.3244532 ]]
ages:  21.55976919416662
[[[48.]
  [48.]
  [44.]
  ...
  [35.]
  [31.]
  [33.]]

 [[45.]
  [44.]
  [43.]
  ...
  [30.]
  [33.]
  [33.]]

 [[45.]
  [45.]
  [46.]
  ...
  [32.]
  [33.]
  [32.]]

 ...

 [[38.]
  [36.]
  [37.]
  ...
  [21.]
  [22.]
  [21.]]

 [[35.]
  [38.]
  [37.]
  ...
  [24.]
  [24.]
  [22.]]

 [[35.]
  [35.]
  [37.]
  ...
  [23.]
  [23.]
  [23.]]]
genders:  [[0.65939975 0.34060025]]
ages:  21.40499946334603


In [23]:
import pandas as pd

In [24]:
#Create dataframe
classification_df = pd.DataFrame(MUG_data, columns = ['dB', 'ID', 'Age', 'Gender'])
classification_df['dB'] = 'MUG'

In [25]:
### Get median age and gender ratio

#Expects dataframe from the database-data
def get_median_age_and_gender(dataframe):
    age_and_gender = []
    for unique_ID in unique_IDs:
        database = dataframe[dataframe['ID'] == unique_ID]['dB'].iloc[0]
        #Using median to get rid of uitschieters
        median_age = dataframe[dataframe['ID'] == unique_ID]['Age'].median()
        if(median_age >=35):
            age = 'O'
        else:
            age = 'Y'
        female_count = dataframe[dataframe['ID'] == unique_ID][dataframe['Gender']=='F'].count()[0]
        male_count = dataframe[dataframe['ID'] == unique_ID][dataframe['Gender']=='M'].count()[0]
        if(male_count == 0.0):
            male_count = 1.0
        ratio = female_count/male_count
        if(ratio <=1.0):
            gender = "M"
        else:
            gender = "F"
        age_and_gender.append([database, unique_ID, age, gender])

    return age_and_gender

In [26]:
#Get array of unique IDs
unique_IDs = list(classification_df['ID'].unique())

## Create classified data

In [27]:
classified_data = get_median_age_and_gender(classification_df)

C:\Users\JeanBV\Miniconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  
C:\Users\JeanBV\Miniconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app


## Newly created database

In [28]:
classified_df = pd.DataFrame(data = classified_data, columns = ['dB', 'ID', 'Age', 'Gender'])

In [29]:
def include_ethnicity(df):
    for i in range(len(df)):
        if(df['dB'].loc[i]=='CASPEAL') or (df['dB'].loc[i]=='JAFFE'):
            df['Ethnicity']='A'
        else:
            df['Ethnicity']='C'
    return df
            

In [30]:
classified_df = include_ethnicity(classified_df)

In [31]:
def create_models(df):
    F = df[df['Gender']=='F']
    M = df[df['Gender']=='M']

    YF = F[F['Age']=='Y']
    YM = M[M['Age']=='Y']

    OF =  F[F['Age']=='O']
    OM =  M[M['Age']=='O']

    YFC = YF[YF['Ethnicity']=='C']
    YMC = YM[YM['Ethnicity']=='C']
    OFC = OF[OF['Ethnicity']=='C']
    OMC = OM[OM['Ethnicity']=='C']

    YFA = YF[YF['Ethnicity']=='A']
    YMA = YM[YM['Ethnicity']=='A']
    OFA = OF[OF['Ethnicity']=='A']
    OMA = OM[OM['Ethnicity']=='A']
    
    return [YFC,YMC,OFC,OMC,YFA,YMA,OFA,OMA]

In [32]:
[YFC,YMC,OFC,OMC,YFA,YMA,OFA,OMA] = create_models(classified_df)

In [33]:
classified_df['label'] = 0 #Insert column name "label"

In [34]:
def classification_models(df):

    #Mapping of the model numbers to the subjects in the classified dataframe
    for i in range(len(YFC.index)):
        df['label'][YFC.index[i]] = 1
    for i in range(len(YMC.index)):
        df['label'][YMC.index[i]] = 2
    for i in range(len(OFC.index)):
        df['label'][OFC.index[i]] = 3
    for i in range(len(OMC.index)):
        df['label'][OMC.index[i]] = 4
    for i in range(len(YFA.index)):
        df['label'][YFA.index[i]] = 5
    for i in range(len(YMA.index)):
        df['label'][YMA.index[i]] = 6
    for i in range(len(OFA.index)):
        df['label'][OFA.index[i]] = 7
    for i in range(len(OMA.index)):
        df['label'][OMA.index[i]] = 8

    return df

In [35]:
model_class = classification_models(classified_df)

C:\Users\JeanBV\Miniconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\JeanBV\Miniconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [36]:
unique_ID = np.unique(MUG[2])
unique_ID

array(['001', '006', '007', '008', '010', '013', '062', '063', '064',
       '082'], dtype='<U3')

In [37]:
# Ge zoekt een ID uit uw MUG en kijkt welke label overeenstemt met die ID
# dan gaat ge al die instanties voor die ID afgaan en dan opslagen in een lijst(?) met bv naam "model 1"
# dan zoekt ge da voor alle IDs die dezelfde labels hebben als die en die voegt ge cst toe aan dat model.
# model zal dan bestaan uit drie soorten files, de sybjID model1, emotion label model1 en xdata_model 1

In [50]:
YFC_X, YFC_Y, YFC_SubjID = [],[],[]
YMC_X, YMC_Y, YMC_SubjID = [],[],[]
OFC_X, OFC_Y, OFC_SubjID = [],[],[]
OMC_X, OMC_Y, OMC_SubjID = [],[],[]
YFA_X, YFA_Y, YFA_SubjID = [],[],[]
YMA_X, YMA_Y, YMA_SubjID = [],[],[]
OFA_X, OFA_Y, OFA_SubjID = [],[],[]
OMA_X, OMA_Y, OMA_SubjID = [],[],[]

def link_label_with_data(npy_data, model_class):
    for ID in np.unique(npy_data[2]):
        #Looks in the numpy file for corresponding suject IDs and looks for the label in the dataframe
        label = model_class[model_class['ID'] == ID]['label'].iloc[0] #Save the label connected to the ID
        index_vals = np.where(npy_data[2] == ID) #Get index values of the ID 
        list_vals = index_vals[0].tolist()
        for index in list_vals:
            model_1 = npy_data[0][index]
            model_2 = list(npy_data[1][index])
            model_3 = npy_data[2][index]
            if(label == 1):
                YFC_X.append(model_1)
                YFC_Y.append(model_2)
                YFC_SubjID.append(model_3)
            elif(label == 2):
                YMC_X.append(model_1)
                YMC_Y.append(model_2)
                YMC_SubjID.append(model_3)
            elif(label == 3):
                OFC_X.append(model_1)
                OFC_Y.append(model_2)
                OFC_SubjID.append(model_3)
            elif(label == 4):
                OMC_X.append(model_1)
                OMC_Y.append(model_2)
                OMC_SubjID.append(model_3)
            elif(label == 5):
                YFA_X.append(model_1)
                YFA_Y.append(model_2)
                YFA_SubjID.append(model_3)
            elif(label == 6):
                YMA_X.append(model_1)
                YMA_Y.append(model_2)
                YMA_SubjID.append(model_3)
            elif(label == 7):
                OFA_X.append(model_1)
                OFA_Y.append(model_2)
                OFA_SubjID.append(model_3)
            elif(label == 8):
                OMA_X.append(model_1)
                OMA_Y.append(model_2)
                OMA_SubjID.append(model_3)
    
    return YFC_X, YFC_Y, YFC_SubjID,YMC_X, YMC_Y, YMC_SubjID,OFC_X, OFC_Y, OFC_SubjID,OMC_X, OMC_Y, OMC_SubjID,YFA_X, YFA_Y, YFA_SubjID,YMA_X, YMA_Y, YMA_SubjID,OFA_X, OFA_Y, OFA_SubjID,OMA_X, OMA_Y, OMA_SubjID
        

In [51]:
YFC_X[0]

IndexError: list index out of range

In [61]:
def show_classified_pictures():
    for i in range(len(YFC_X)):
        cv2.imshow(YFC_SubjID[i], YFC_X[i].astype('uint8'))
        cv2.waitKey()
        cv2.destroyAllWindows()


### Sort images in folders

In [54]:
link_label_with_data(MUG, model_class)

([array([[[37.],
          [28.],
          [14.],
          ...,
          [ 5.],
          [ 4.],
          [ 7.]],
  
         [[31.],
          [21.],
          [12.],
          ...,
          [ 4.],
          [ 4.],
          [ 5.]],
  
         [[23.],
          [19.],
          [13.],
          ...,
          [ 7.],
          [ 4.],
          [ 4.]],
  
         ...,
  
         [[ 1.],
          [ 1.],
          [ 1.],
          ...,
          [ 4.],
          [ 9.],
          [10.]],
  
         [[ 1.],
          [ 1.],
          [ 1.],
          ...,
          [ 5.],
          [11.],
          [12.]],
  
         [[ 2.],
          [ 5.],
          [ 3.],
          ...,
          [ 4.],
          [10.],
          [14.]]]), array([[[25.],
          [13.],
          [12.],
          ...,
          [ 4.],
          [ 5.],
          [ 6.]],
  
         [[23.],
          [13.],
          [11.],
          ...,
          [ 7.],
          [ 5.],
          [ 5.]],
  
         [[19.],
 

In [43]:
def create_emotion(database):
    emotion_list = []
    for i in range(len(database)):
        if(np.array_equal(angry,database[i])):
            emotion = 'angry'
            emotion_list.append(emotion)
        elif(np.array_equal(neutral,database[i])):
            emotion = 'neutral'
            emotion_list.append(emotion)
        elif(np.array_equal(disgust,database[i])):
            emotion = 'disgust'
            emotion_list.append(emotion)
        elif(np.array_equal(fear,database[i])):
            emotion = 'fear'
            emotion_list.append(emotion)
        elif(np.array_equal(happy,database[i])):
            emotion = 'happy'
            emotion_list.append(emotion)
        elif(np.array_equal(sad,database[i])):
            emotion = 'sad'
            emotion_list.append(emotion)
        elif(np.array_equal(surprise,database[i])):
            emotion = 'surprise'
            emotion_list.append(emotion)
    return emotion_list

In [68]:
YFC_Emotion = create_emotion(YFC_Y)
YMC_Emotion = create_emotion(YMC_Y)
YFC_Emotion = create_emotion(YFC_Y)
YMC_Emotion = create_emotion(YMC_Y)
OFC_Emotion = create_emotion(OFC_Y)
OMC_Emotion = create_emotion(OMC_Y)
YFA_Emotion = create_emotion(YFA_Y)
YMA_Emotion = create_emotion(YMA_Y)
OFA_Emotion = create_emotion(OFA_Y)
OMA_Emotion = create_emotion(OMA_Y)

In [69]:
def show_classified_pictures():
    for i in range(len(YFC_X)):
        cv2.imshow(list_emotion[i] + YFC_SubjID[i], YFC_X[i].astype('uint8'))
        cv2.waitKey()
        cv2.destroyAllWindows()

In [102]:
def make_directories_and_save_images():
    subjects_dir='Subjects'
    male_dir='Male_Subjects'
    female_dir='Female_Subjects'
    old_male_dir='Old_Male_Subjects'
    old_female_dir='Old_Female_Subjects'
    young_male_dir='Young_Male_Subjects'
    young_female_dir='Young_Female_Subjects'
    ethnicity_asian_dir = "Asian"
    ethnicity_european_dir = "European"
    
    if not os.path.exists(subjects_dir):
        os.makedirs(subjects_dir)
        
    current_directory = os.path.abspath(subjects_dir)
    male_dir = os.path.join(current_directory, male_dir)
    female_dir = os.path.join(current_directory, female_dir)
    
    if not os.path.exists(male_dir):
        os.makedirs(male_dir)
        
    current_directory = os.path.abspath(male_dir)
    old_male_path = os.path.join(current_directory, old_male_dir)
    young_male_path = os.path.join(current_directory, young_male_dir)
    
    if not os.path.exists(old_male_path):
        os.makedirs(old_male_path)
        
    current_directory = os.path.abspath(old_male_path)
    ethnicity_asian_path = os.path.join(current_directory, ethnicity_asian_dir)
    ethnicity_european_path = os.path.join(current_directory, ethnicity_european_dir)

    if not os.path.exists(ethnicity_asian_path):
        #old male asian
        os.makedirs(ethnicity_asian_path)
    if not os.path.exists(ethnicity_european_path):
        #old male european
        os.makedirs(ethnicity_european_path)

    if not os.path.exists(young_male_path):
        os.makedirs(young_male_path)
        
    current_directory = os.path.abspath(young_male_path)
    ethnicity_asian_path = os.path.join(current_directory, ethnicity_asian_dir)
    ethnicity_european_path = os.path.join(current_directory, ethnicity_european_dir)

    if not os.path.exists(ethnicity_asian_path):
        #young male asian
        os.makedirs(ethnicity_asian_path)
    for i in range(len(YMA_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ YMA_SubjID[i]+"_"+YMA_Emotion[i] +"_"+str(i)+ ".jpg", YMA_X[i].astype('uint8'))
   
        
    if not os.path.exists(ethnicity_european_path):
        #young male european
        os.makedirs(ethnicity_european_path)
    for i in range(len(YMC_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ YMC_SubjID[i]+"_"+YMC_Emotion[i] +"_"+str(i)+ ".jpg", YMC_X[i].astype('uint8'))
    
                
                
    if not os.path.exists(female_dir):
        os.makedirs(female_dir)
        
    current_directory = os.path.abspath(female_dir)
    old_female_path = os.path.join(current_directory, old_female_dir)
    young_female_path = os.path.join(current_directory, young_female_dir)
    
    if not os.path.exists(old_female_path):
        os.makedirs(old_female_path)
        
    current_directory = os.path.abspath(old_female_path)
    ethnicity_asian_path = os.path.join(current_directory, ethnicity_asian_dir)
    ethnicity_european_path = os.path.join(current_directory, ethnicity_european_dir)

    if not os.path.exists(ethnicity_asian_path):
        #old female asian
        os.makedirs(ethnicity_asian_path)
    for i in range(len(OFA_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ OFA_SubjID[i]+"_"+OFA_Emotion[i] +"_"+str(i)+ ".jpg", OFA_X[i].astype('uint8'))
        
    if not os.path.exists(ethnicity_european_path):
        #old female european
        os.makedirs(ethnicity_european_path)
    for i in range(len(OFC_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ OFC_SubjID[i]+"_"+OFC_Emotion[i] +"_"+str(i)+ ".jpg", OFC_X[i].astype('uint8'))
    

    if not os.path.exists(young_female_path):
        os.makedirs(young_female_path)
        
    current_directory = os.path.abspath(young_female_path)
    ethnicity_asian_path = os.path.join(current_directory, ethnicity_asian_dir)
    ethnicity_european_path = os.path.join(current_directory, ethnicity_european_dir)

    if not os.path.exists(ethnicity_asian_path):
        #young female asian
        os.makedirs(ethnicity_asian_path)
    for i in range(len(YFA_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ YFA_SubjID[i]+"_"+YFA_Emotion[i] +"_"+str(i)+ ".jpg", YFA_X[i].astype('uint8'))
    if not os.path.exists(ethnicity_european_path):
        #young female european
        os.makedirs(ethnicity_european_path)
    for i in range(len(YFC_Emotion)):
        cv2.imwrite(ethnicity_european_path +"\\"+ YFC_SubjID[i]+"_"+YFC_Emotion[i] +"_"+str(i)+ ".jpg", YFC_X[i].astype('uint8'))
        
    return subjects_dir, male_dir, female_dir, old_male_dir, old_female_dir, young_male_dir, young_female_dir

In [ ]:
make_directories_and_save_images()

In [93]:
len(YFC_Emotion)

1666

In [44]:
classification_df

dB   ID  Age Gender
0   MUG  001   23      F
1   MUG  001   23      F
2   MUG  001   22      F
3   MUG  001   22      F
4   MUG  001   22      F
5   MUG  001   22      F
6   MUG  001   23      F
7   MUG  001   22      F
8   MUG  006   22      F
9   MUG  006   22      F
10  MUG  006   22      F
11  MUG  006   22      F
12  MUG  006   22      F
13  MUG  006   22      F
14  MUG  006   22      F
15  MUG  006   22      F
16  MUG  006   23      F
17  MUG  006   23      F
18  MUG  007   25      M
19  MUG  007   25      M
20  MUG  007   24      M
21  MUG  007   24      M
22  MUG  007   24      M
23  MUG  007   24      M
24  MUG  007   24      M
25  MUG  007   24      M
26  MUG  007   24      M
27  MUG  007   24      M
28  MUG  007   24      M
29  MUG  007   24      M
..  ...  ...  ...    ...
60  MUG  013   21      F
61  MUG  013   21      F
62  MUG  013   21      F
63  MUG  013   20      F
64  MUG  013   19      F
65  MUG  013   19      F
66  MUG  062   22      M
67  MUG  062   21      M
68  MUG  062   36      F
69  MUG  062   21      M
70  MUG  062   21      M
71  MUG  062   21      M
72  MUG  062   21      M
73  MUG  062   22      M
74  MUG  063   18      M
75  MUG  063   18      M
76  MUG  063   18      M
77  MUG  063   18      M
78  MUG  064   21      F
79  MUG  064   22      F
80  MUG  064   22      F
81  MUG  064   22      F
82  MUG  064   22      F
83  MUG  064   23      F
84  MUG  082   21      F
85  MUG  082   21      F
86  MUG  082   22      F
87  MUG  082   21      F
88  MUG  082   21      F
89  MUG  082   21      F

[90 rows x 4 columns]

In [91]:
subjects_dir, male_dir, female_dir, old_male_dir, old_female_dir, young_male_dir, young_female_dir = make_directories()

In [82]:
os.path.abspath("test")x

'C:\\Users\\JeanBV\\Documents\\Thesis_Christiaan_Jean\\Custom_Dexpression\\test'

In [ ]:
YFC_X, YFC_Y, YFC_SubjID = [],[],[]
YMC_X, YMC_Y, YMC_SubjID = [],[],[]
OFC_X, OFC_Y, OFC_SubjID = [],[],[]
OMC_X, OMC_Y, OMC_SubjID = [],[],[]
YFA_X, YFA_Y, YFA_SubjID = [],[],[]
YMA_X, YMA_Y, YMA_SubjID = [],[],[]
OFA_X, OFA_Y, OFA_SubjID = [],[],[]
OMA_X, OMA_Y, OMA_SubjID = [],[],[]

In [ ]:
# def create_classification_dirs():
subjects_dir, male_dir, female_dir, old_male_dir, old_female_dir, young_male_dir, young_female_dir = make_directories()

path_female = classification_df[(classification_df['Gender']=='F')]
path_male = classification_df[(classification_df['Gender']=='M')]
female_young = path_female[path_female['Age']=='Y']['Path']
female_old = path_female[path_female['Age']=='O']['Path']
male_young = path_male[path_male['Age']=='Y']['Path']
male_old = path_male[path_male['Age']=='O']['Path']
try:
    for path in female_old:
        shutil.copy2(path, subjects_dir+'\\'+female_dir +'\\'+old_female_dir ) # complete target filename given
    for path in male_old:
        shutil.copy2(path,subjects_dir+'\\'+ male_dir +'\\'+old_male_dir)
    for path in female_young:
        shutil.copy2(path, subjects_dir+'\\'+female_dir +'\\'+young_female_dir)
    for path in male_young:
        shutil.copy2(path,subjects_dir+'\\'+ male_dir +'\\'+young_male_dir)
except Exception as e:
    print("Folder already exists")